###网易系(126/163/yeah)邮箱配置
#spring:
#  mail:
#    host: smtp.163.com #发送邮件服务器
#    username: hyfmail****@163.com #发送邮件的邮箱地址
#    password: ************** #客户端授权码，不是邮箱密码,网易的是自己设置的
#    properties.mail.smtp.port: 465 #465或者994
#    from: hyfmail****@163.com # 发送邮件的地址，和上面username一致
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8


# QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 24********@qq.com #发送邮件的邮箱地址
    password: **************** #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 24********@qq.com # 发送邮件的地址，和上面username一致
    protocol: smtps  #如果使用端口为465，将protocol的smtp改为smtps；配置文件端口为587，则可以使用smtp。
  #开启加密验证
  properties.mail.smtp.ssl.enable: true
